### ISSUE TITLE
Source code explanation

### ISSUE THREAD

**Issue by Jannet537** [HevLfreis/TrafficLight-Detector#2]
Can you please give a brief explanation of the source code so that I can understand this project better?

**Comment by EqunSpace** [comment]
mo too

**Comment by HevLfreis** [comment]
use hough circle transform to detect circle in the img. use different color masks to classifiy red green or yellow, you can refer to this doc

https://opencv-python-tutroals.readthedocs.io/en/latest/py_tutorials/py_imgproc/py_houghcircles/py_houghcircles.html
